build: update build system

diff --git a/bin/release/postrelease b/bin/release/postrelease
--- a/bin/release/postrelease
+++ b/bin/release/postrelease
@@ -1,5 +1,20 @@
 #!/bin/bash
 
-# send all tags to remote
-git push --follow-tags origin main
-git push --tags
+REQUIRED_TOOLS=(
+  git
+)
+
+for TOOL in "${REQUIRED_TOOLS[@]}"; do
+  if ! command -v "${TOOL}" >/dev/null; then
+    echo "${TOOL} is required... "
+    exit 1
+  fi
+done
+
+# adding data directory for new build information
+git add data/dnb
+git commit --signoff --amend --no-edit
+
+# push release to GitHub
+git push origin main --follow-tags
+git push origin --tags
